name: booking_monitor_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0 # Updated based on lock file
  flutter_local_notifications: ^17.2.4 # Updated based on lock file
  intl: ^0.19.0
  url_launcher: ^6.3.2 # Updated based on lock file

  # --- FCM Dependencies ---
  firebase_core: ^4.2.0 # Added (Version from your lock file)
  firebase_messaging: ^16.0.3 # Added (Version from your lock file)
  # --- End FCM Dependencies ---

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg