// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDABgKLk-IZFA0mKYMAL-0kYt4YKgeLQ4k',
    appId: '1:916440860862:web:e4fa82d5218030306f76ef',
    messagingSenderId: '916440860862',
    projectId: 'rich--assistant',
    authDomain: 'rich--assistant.firebaseapp.com',
    storageBucket: 'rich--assistant.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZPmlpVST_bCPv8MxiM4H73Ecoh27ILeo',
    appId: '1:916440860862:android:ac72cdce71fabcad6f76ef',
    messagingSenderId: '916440860862',
    projectId: 'rich--assistant',
    storageBucket: 'rich--assistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmPu7m_Gw4Qgw7TaoIGToo_oiLxPWM2bk',
    appId: '1:916440860862:ios:91db0e7a712863606f76ef',
    messagingSenderId: '916440860862',
    projectId: 'rich--assistant',
    storageBucket: 'rich--assistant.firebasestorage.app',
    iosBundleId: 'com.example.bookingMonitorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmPu7m_Gw4Qgw7TaoIGToo_oiLxPWM2bk',
    appId: '1:916440860862:ios:91db0e7a712863606f76ef',
    messagingSenderId: '916440860862',
    projectId: 'rich--assistant',
    storageBucket: 'rich--assistant.firebasestorage.app',
    iosBundleId: 'com.example.bookingMonitorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDABgKLk-IZFA0mKYMAL-0kYt4YKgeLQ4k',
    appId: '1:916440860862:web:49e2c7585f2cfee26f76ef',
    messagingSenderId: '916440860862',
    projectId: 'rich--assistant',
    authDomain: 'rich--assistant.firebaseapp.com',
    storageBucket: 'rich--assistant.firebasestorage.app',
  );
}
